name: CI

on:
  push:
    branches: [develop]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: noaaepic/ubuntu22.04-intel-spack-unified:srw-dev-v1.5.1
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
