name: Intel Linux Build and Test
on: [push, pull_request, workflow_dispatch]

# Use custom shell with -l so .bash_profile is sourced which loads intel/oneapi/setvars.sh
# without having to do it in manually every step
defaults:
  run:
    shell: bash -leo pipefail {0}

# Set I_MPI_CC/F90 so IntelLLVM is used.
env:
  cache_key: intel
  CC: mpiicx
  FC: mpiifx
  CXX: mpiicpx
  I_MPI_CC: icx
  I_MPI_F90: ifx
  I_MPI_CXX: icpx

# The jobs are split into:
# 1. a dependency build step (setup), and
# 2. a nexus build and test step (nexus)
# The setup is run once and the environment is cached,
# so each subsequent build and test of nexus can reuse the cached
# dependencies to save time (and compute).

jobs:
  setup:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout  # this is to get the ci/spack.yaml file
        uses: actions/checkout@v3
        with:
            path: nexus

      # Cache spack, compiler and dependencies
      - name: cache-env
        id: cache-env
        uses: actions/cache@v3
        with:
          path: |
            spack
            ~/.spack
            /opt/intel
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('nexus/ci/spack.yaml') }}

      - name: install-intel-compilers
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update
          sudo apt-get install intel-oneapi-dev-utilities intel-oneapi-mpi-devel intel-oneapi-openmp intel-oneapi-compiler-fortran intel-oneapi-compiler-dpcpp-cpp
          echo "source /opt/intel/oneapi/setvars.sh" >> ~/.bash_profile

      # Install dependencies using Spack
      - name: install-dependencies-with-spack
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
          sudo mv /usr/local /usr/local_mv
          git clone -c feature.manyFiles=true https://github.com/JCSDA/spack.git
          source spack/share/spack/setup-env.sh
          sed "s/\[oneapi, gcc@10:10, apple-clang@14\]/\[oneapi\]/g" nexus/ci/spack.yaml > spack_ci.yaml
          spack env create nexus-env spack_ci.yaml
          spack env activate nexus-env
          spack compiler find
          sudo apt install cmake
          spack external find
          spack config add "packages:all:prefer:'%oneapi'"
          spack config add "packages:mpi:require:intel-oneapi-mpi"
          intel_mpi_version=$(basename $(realpath /opt/intel/oneapi/mpi/latest))
          sed -i "s|^  packages:|  packages:\n    intel-oneapi-mpi:\n      buildable: false\n      externals:\n      - spec: intel-oneapi-mpi@${intel_mpi_version}\n        prefix: /opt/intel/oneapi|" $SPACK_ENV/spack.yaml
          spack config add "packages:python:require:'@3.11'"
          cat $SPACK_ENV/spack.yaml
          spack concretize
          spack install --dirty --show-log-on-error --fail-fast
          spack clean --all

  nexus:
    needs: setup
    runs-on: ubuntu-24.04

    steps:
      - name: install-intel
        run: |
          echo "source /opt/intel/oneapi/setvars.sh" >> ~/.bash_profile

      - name: checkout
        uses: actions/checkout@v3
        with:
            path: nexus
            submodules: recursive

      - name: cache-env
        id: cache-env
        uses: actions/cache@v3
        with:
          path: |
            spack
            ~/.spack
            /opt/intel
          key: spack-${{ runner.os }}-${{ env.cache_key }}-${{ hashFiles('nexus/ci/spack.yaml') }}

      - name: build
        run: |
          source spack/share/spack/setup-env.sh
          spack env activate nexus-env
          export CC=mpiicx
          export FC=mpiifx
          cd nexus
          mkdir -p build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=../install ..
          make -j2 VERBOSE=1
          make install

      - name: ctest
        run: |
          source spack/share/spack/setup-env.sh
          spack env activate nexus-env
          cd nexus
          set -x
          bin="$PWD/build/bin/nexus"
          failed=0
          cd tests/cases
          for d in *; do
            cd $d
            $bin -c NEXUS_Config.rc -r grid_spec.nc || failed=1
            if [[ "$failed" == 1 ]]; then
              tail -n 20 NEXUS.log
              cat PET0.ESMF_LogFile
              exit 1
            fi
            cd ..
          done
